MET_WEATHER_CONDITIONS = {
    "clearsky_day": "Clear Sky",
    "clearsky_night": "Clear Sky",
    "fair_day": "Fair",
    "fair_night": "Fair",
    "partlycloudy_day": "Partly Cloudy",
    "partlycloudy_night": "Partly Cloudy",
    "cloudy": "Cloudy",
    "lightrainshowers_day": "Light Rain Showers",
    "lightrainshowers_night": "Light Rain Showers",
    "rainshowers_day": "Rain Showers",
    "rainshowers_night": "Rain Showers",
    "heavyrainshowers_day": "Heavy Rain Showers",
    "heavyrainshowers_night": "Heavy Rain Showers",
    "lightsnowshowers_day": "Light Snow Showers",
    "lightsnowshowers_night": "Light Snow Showers",
    "snowshowers_day": "Snow Showers",
    "snowshowers_night": "Snow Showers",
    "heavysnowshowers_day": "Heavy Snow Showers",
    "heavysnowshowers_night": "Heavy Snow Showers",
    "lightssleetshowers_day": "Light Sleet Showers",
    "lightssleetshowers_night": "Light Sleet Showers",
    "sleetshowers_day": "Sleet Showers",
    "sleetshowers_night": "Sleet Showers",
    "heavysleetshowers_day": "Heavy Sleet Showers",
    "heavysleetshowers_night": "Heavy Sleet Showers",
    "lightsnow": "Light Snow",
    "snow": "Snow",
    "heavysnow": "Heavy Snow",
    "lightrain": "Light Rain",
    "rain": "Rain",
    "heavyrain": "Heavy Rain",
    "lightsleet": "Light sleet",
    "sleet": "Sleet",
    "heavysleet": "Heavy sleet",
    "lightssleet": "Light sleet",
    "lightsnowandthunder": "Light snow and thunder",
    "snowandthunder": "Snow and thunder",
    "heavysnowandthunder": "Heavy snow and thunder",
    "lightrainandthunder": "Light rain and thunder",
    "rainandthunder": "Rain and thunder",
    "heavyrainandthunder": "Heavy rain and thunder",
    "lightsleetandthunder": "Light sleet and thunder",
    "sleetandthunder": "Sleet and thunder",
    "heavysleetandthunder": "Heavy sleet and thunder",
    "lightssleetshowersandthunder_day": "Light sleet showers and thunder",
    "lightssleetshowersandthunder_night": "Light sleet showers and thunder",
    "sleetshowersandthunder_day": "Sleet showers and thunder",
    "sleetshowersandthunder_night": "Sleet showers and thunder",
    "heavysleetshowersandthunder_day": "Heavy sleet showers and thunder",
    "heavysleetshowersandthunder_night": "Heavy sleet showers and thunder",
    "lightsnowshowersandthunder_day": "Light snow showers and thunder",
    "lightsnowshowersandthunder_night": "Light snow showers and thunder",
    "snowshowersandthunder_day": "Snow showers and thunder",
    "snowshowersandthunder_night": "Snow showers and thunder",
    "heavysnowshowersandthunder_day": "Heavy snow showers and thunder",
    "heavysnowshowersandthunder_night": "Heavy snow showers and thunder",
    "lightrainshowersandthunder_day": "Light rain showers and thunder",
    "lightrainshowersandthunder_night": "Light rain showers and thunder",
    "rainshowersandthunder_day": "Rain showers and thunder",
    "rainshowersandthunder_night": "Rain showers and thunder",
    "heavyrainshowersandthunder_day": "Heavy rain showers and thunder",
    "heavyrainshowersandthunder_night": "Heavy rain showers and thunder",
}
